param(
 [switch]$Start,
 [switch]$AllowExistingEnvironment
)
$ErrorActionPreference='Stop'
$directory=(Resolve-Path $PSScriptRoot).Path
Set-Location $directory
$manifest=Join-Path $directory 'SHA256SUMS.txt'
if(!(Test-Path $manifest)){throw 'Missing SHA256SUMS.txt'}
foreach($line in Get-Content $manifest){
 if($line -notmatch '^([0-9a-fA-F]{64})  (.+)$'){throw 'Invalid checksum manifest line'}
 $expected=$Matches[1];$relative=$Matches[2]
 if($relative -match '(^/|^\\|\.\.|:)'){throw 'Unsafe relative path in checksum manifest'}
 $file=Join-Path $directory $relative
 if(!(Test-Path $file)){throw "Missing bundle file: $relative"}
 $actual=(Get-FileHash -Algorithm SHA256 $file).Hash
 if($actual -ine $expected){throw "Checksum mismatch: $relative"}
}
Write-Output 'OFFLINE_CHECKSUMS=PASS'
& docker info *> $null
if($LASTEXITCODE -ne 0){throw 'Docker Engine unavailable'}
& docker compose version *> $null
if($LASTEXITCODE -ne 0){throw 'Docker Compose v2 unavailable'}
$expectedPlatform=(Get-Content (Join-Path $directory 'PLATFORM.txt') -Raw).Trim()
$hostPlatform=(& docker info --format '{{.OSType}}/{{.Architecture}}').Trim()
if($expectedPlatform -ne $hostPlatform){throw "Docker platform mismatch: package=$expectedPlatform target=$hostPlatform. Build an architecture-matched bundle."}
Write-Output ('OFFLINE_PLATFORM='+$hostPlatform)
$envPath=Join-Path $directory '.env.production'
if(!(Test-Path $envPath)){
 throw 'Missing .env.production: create it from .env.production.example using unique strong secrets before deploying. No credentials are generated by this script.'
}
$content=Get-Content -Raw $envPath
foreach($key in @('JINGCANG_SESSION_SECRET','JINGCANG_VIEWER_SECRET','JINGCANG_ADMIN_INITIAL_PASSWORD')){
 $match=[regex]::Match($content,"(?m)^$key=(.+)$")
 if(!$match.Success -or $match.Groups[1].Value.Trim().Length -lt 12 -or $match.Groups[1].Value.Contains('change-me')){
  throw "Missing or placeholder production security variable: $key"
 }
}
$imageTar=Join-Path $directory 'images/production-images.tar'
& docker load -i $imageTar
if($LASTEXITCODE -ne 0){throw 'docker load failed'}
$images=@(& docker compose --env-file $envPath -f compose.production.yaml config --images)
if($LASTEXITCODE -ne 0){throw 'Compose config invalid'}
foreach($image in ($images | Where-Object {$_} | Sort-Object -Unique)){
 & docker image inspect $image *> $null
 if($LASTEXITCODE -ne 0){throw "Archive did not provide required image: $image"}
}
Write-Output 'OFFLINE_IMAGES=PASS'
if($Start){
 & docker compose --env-file $envPath -f compose.production.yaml up -d --pull never --no-build
 if($LASTEXITCODE -ne 0){throw 'Offline Docker Compose failed'}
 Write-Output 'OFFLINE_STACK_STARTED=PASS'
}else{
 Write-Output 'OFFLINE_READY=PASS: pass -Start after verifying your production configuration'
}
